# Site settings
title: SEA2NY
subtitle: "Daniel’s Cross-Country Motorcycle Trip from Seattle, WA, to Brooklyn, NY"
email: daniel@gasienica.ch
description: "Daniel Gasienica’s Cross-Country Motorcycle Trip from Seattle, WA, to Brooklyn, NY."
baseurl: ""
url: "http://www.sea2ny.com"
twitter_username: "gasi"
github_username:  "gasi"
instagram_username: "gasi"

gems:
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
